export const userData = [
    {
      name: 'Jan',
      "Active User": 4000,
      
    },
    {
      name: 'Feb',
      "Active User": 3000,
      
    },
    {
      name: 'Mar',
      "Active User": 2000,
      
    },
    {
      name: 'Apr',
      "Active User": 2780,
      
    },
    {
      name: 'May',
      "Active User": 1890,
      
    },
    {
      name: 'June',
      "Active User": 2390,
      
    },
    {
      name: 'July',
      "Active User": 3490,
      
    },
  ];

  export const userRows = [
    { id: 1,
        username: 'Win A', 
        avatar: "https://images.pexels.com/photos/187069/pexels-photo-187069.jpeg?cs=srgb&dl=pexels-digital-buggu-187069.jpg&fm=jpg", 
        email: "win@gmail.com",
        status: "active",
        transaction: "$120",
    },
    { id: 2,
        username: 'Win A', 
        avatar: "https://images.pexels.com/photos/187069/pexels-photo-187069.jpeg?cs=srgb&dl=pexels-digital-buggu-187069.jpg&fm=jpg", 
        email: "win@gmail.com",
        status: "active",
        transaction: "$120",
    },
    { id: 3,
        username: 'Win A', 
        avatar: "https://images.pexels.com/photos/187069/pexels-photo-187069.jpeg?cs=srgb&dl=pexels-digital-buggu-187069.jpg&fm=jpg", 
        email: "win@gmail.com",
        status: "active",
        transaction: "$120",
    },
    { id: 4,
        username: 'Win A', 
        avatar: "https://images.pexels.com/photos/187069/pexels-photo-187069.jpeg?cs=srgb&dl=pexels-digital-buggu-187069.jpg&fm=jpg", 
        email: "win@gmail.com",
        status: "active",
        transaction: "$120",
    },
    { id: 5,
        username: 'Win A', 
        avatar: "https://images.pexels.com/photos/187069/pexels-photo-187069.jpeg?cs=srgb&dl=pexels-digital-buggu-187069.jpg&fm=jpg", 
        email: "win@gmail.com",
        status: "active",
        transaction: "$120",
    },
    { id: 6,
        username: 'Win A', 
        avatar: "https://images.pexels.com/photos/187069/pexels-photo-187069.jpeg?cs=srgb&dl=pexels-digital-buggu-187069.jpg&fm=jpg", 
        email: "win@gmail.com",
        status: "active",
        transaction: "$120",
    },


   
  ];
  export const productRows = [
    { id: 1,
        name: 'Macbook', 
        img: "https://images.pexels.com/photos/187069/pexels-photo-187069.jpeg?cs=srgb&dl=pexels-digital-buggu-187069.jpg&fm=jpg", 
        price: "win@gmail.com",
        stock: "120",
        status: "active",
    },
    { id: 2,
      name: 'Macbook', 
      img: "https://images.pexels.com/photos/187069/pexels-photo-187069.jpeg?cs=srgb&dl=pexels-digital-buggu-187069.jpg&fm=jpg", 
      price: "win@gmail.com",
      stock: "120",
      status: "active",
  },
  { id: 3,
      name: 'Macbook', 
      img: "https://images.pexels.com/photos/187069/pexels-photo-187069.jpeg?cs=srgb&dl=pexels-digital-buggu-187069.jpg&fm=jpg", 
      price: "win@gmail.com",
      stock: "120",
      status: "active",
  },
  { id: 4,
      name: 'Macbook', 
      img: "https://images.pexels.com/photos/187069/pexels-photo-187069.jpeg?cs=srgb&dl=pexels-digital-buggu-187069.jpg&fm=jpg", 
      price: "win@gmail.com",
      stock: "120",
      status: "active",
  },
  { id: 5,
      name: 'Macbook', 
      img: "https://images.pexels.com/photos/187069/pexels-photo-187069.jpeg?cs=srgb&dl=pexels-digital-buggu-187069.jpg&fm=jpg", 
      price: "win@gmail.com",
      stock: "120",
      status: "active",
  },
  { id: 6,
      name: 'Macbook', 
      img: "https://images.pexels.com/photos/187069/pexels-photo-187069.jpeg?cs=srgb&dl=pexels-digital-buggu-187069.jpg&fm=jpg", 
      price: "win@gmail.com",
      stock: "120",
      status: "active",
  },
  { id: 7,
    name: 'Macbook', 
    img: "https://images.pexels.com/photos/187069/pexels-photo-187069.jpeg?cs=srgb&dl=pexels-digital-buggu-187069.jpg&fm=jpg", 
    price: "win@gmail.com",
    stock: "120",
    status: "active",
},
{ id: 8,
  name: 'Macbook', 
  img: "https://images.pexels.com/photos/187069/pexels-photo-187069.jpeg?cs=srgb&dl=pexels-digital-buggu-187069.jpg&fm=jpg", 
  price: "win@gmail.com",
  stock: "120",
  status: "active",
},
{ id: 9,
  name: 'Macbook', 
  img: "https://images.pexels.com/photos/187069/pexels-photo-187069.jpeg?cs=srgb&dl=pexels-digital-buggu-187069.jpg&fm=jpg", 
  price: "win@gmail.com",
  stock: "120",
  status: "active",
},
{ id: 10,
  name: 'Macbook', 
  img: "https://images.pexels.com/photos/187069/pexels-photo-187069.jpeg?cs=srgb&dl=pexels-digital-buggu-187069.jpg&fm=jpg", 
  price: "win@gmail.com",
  stock: "120",
  status: "active",
},
  ];

  export const productData = [
    {
      name: 'Jan',
      "Sales": 4000,
      
    },
    {
      name: 'Feb',
      "Sales": 3000,
      
    },
    {
      name: 'March',
      "Sales": 3000,
      
    },
  ];